### ISSUE TITLE
664 Banner images

### ISSUE THREAD

**Issue by cmadland** [ma-lead/ldrs664#2]
The banner images in each unit look great, but we need  alt-text or an explanation of the image in the  caption. Will test

**Comment by cmadland** [comment]
I've updated the banner in u1...the text is now in the caption and it is also in the alt-text when you hover overt he image. Thoughts?

```
![Guiding Questions: What does it mean to be authentic in teaching and learning? What is the facilitator's role in creating spaces for authentic learning?](assets/unit1/LDRS664-BannerUnit1.jpg "What does it mean to be authentic in teaching and learning? What is the facilitator's role in creating spaces for authentic learning?")
```

The first bit, in the square brackets, is the caption. the bit between quote marks is the alt-text.

**Comment by kmarjanovic** [comment]
Hmm...Is there a way to do alt text that doesn't show...like the hover feature?

**Comment by kmarjanovic** [comment]
For more complicated images for example - we wouldn't show the text & graphic.  I'll try to look for an example.

**Comment by kmarjanovic** [comment]
How about this hover text: https://ma-lead.github.io/ldrs664/the-heart-of-a-teacher.html

**Comment by MeeksonHundoo** [comment]
Hello @kmarjanovic and @cmadland should we start following the hover text method for all images? also, can we close this request? or do should I change the descriptions on all the images in this course to the hover method as shown above by Kelly?

**Comment by kmarjanovic** [comment]
Good question!
I think as long as we have the alt text, that should be fine, right?
![alt text](file)

We should reserve hover for definitions, or other activities.  @cmadland what do you think.
Before we close this issue, could you check that the 664 banners have alt text?

**Comment by MeeksonHundoo** [comment]
@kmarjanovic all the banners in 664 have alt text. Closing this issue
